#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend-service"
VENV_DIR="$ROOT_DIR/.venv"
FRONTEND_DIR="$ROOT_DIR/frontend-macos"

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required" >&2
  exit 1
fi

python3 -m venv "$VENV_DIR"
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

python -m pip install --upgrade pip
python -m pip install -e "$BACKEND_DIR"

cat > "$ROOT_DIR/.env.local" << ENV
STASH_BACKEND_URL=http://127.0.0.1:8765
ENV

mkdir -p "$FRONTEND_DIR/Config"
cat > "$FRONTEND_DIR/Config/Backend.xcconfig" << XCCONFIG
// Auto-generated by scripts/install_stack.sh
STASH_BACKEND_URL = http://127.0.0.1:8765
XCCONFIG

echo "Stack install complete"
echo "- Backend venv: $VENV_DIR"
echo "- Frontend config: $FRONTEND_DIR/Config/Backend.xcconfig"
echo "- Run backend: ./scripts/run_backend.sh"
